function [pred,errors]  = calculate_mog_error( p1,mu1,vary1,x_1,...
                                    p2,mu2,vary2,x_2,...
                                    p3,mu3,vary3,x_3,...
                                    p4,mu4,vary4,x_4,...
                                    p5,mu5,vary5,x_5,...
                                    p6,mu6,vary6,x_6,...
                                    p7,mu7,vary7,x_7)
n = size(x_1,2) + size(x_2,2) +size(x_3,2)+size(x_4,2)+size(x_5,2)+size(x_6,2)+size(x_7,2);     
%%
train1 = [mogLogProb(p1,mu1,vary1,x_1);...
                mogLogProb(p2,mu2,vary2,x_1);...
                mogLogProb(p3,mu3,vary3,x_1);...
                mogLogProb(p4,mu4,vary4,x_1);...
                mogLogProb(p5,mu5,vary5,x_1);...
                mogLogProb(p6,mu6,vary6,x_1);...
                mogLogProb(p7,mu7,vary7,x_1)];
    [maxval,maxind1] = max(train1);
    train1errors = sum( maxind1 ~= 1);
    %%
        train2 = [mogLogProb(p1,mu1,vary1,x_2);...
                mogLogProb(p2,mu2,vary2,x_2);...
                mogLogProb(p3,mu3,vary3,x_2);...
                mogLogProb(p4,mu4,vary4,x_2);...
                mogLogProb(p5,mu5,vary5,x_2);...
                mogLogProb(p6,mu6,vary6,x_2);...
                mogLogProb(p7,mu7,vary7,x_2)];
    [maxval,maxind2] = max(train2);
    train2errors = sum( maxind2 ~= 2);
    
        train3 = [mogLogProb(p1,mu1,vary1,x_3);...
                mogLogProb(p2,mu2,vary2,x_3);...
                mogLogProb(p3,mu3,vary3,x_3);...
                mogLogProb(p4,mu4,vary4,x_3);...
                mogLogProb(p5,mu5,vary5,x_3);...
                mogLogProb(p6,mu6,vary6,x_3);...
                mogLogProb(p7,mu7,vary7,x_3)];
    [~,maxind3] = max(train3);
    train3errors = sum( maxind3 ~= 3);
    
        train4 = [mogLogProb(p1,mu1,vary1,x_4);...
                mogLogProb(p2,mu2,vary2,x_4);...
                mogLogProb(p3,mu3,vary3,x_4);...
                mogLogProb(p4,mu4,vary4,x_4);...
                mogLogProb(p5,mu5,vary5,x_4);...
                mogLogProb(p6,mu6,vary6,x_4);...
                mogLogProb(p7,mu7,vary7,x_4)];
    [~,maxind4] = max(train4);
    train4errors = sum( maxind4 ~= 4);
    
        train5 = [mogLogProb(p1,mu1,vary1,x_5);...
                mogLogProb(p2,mu2,vary2,x_5);...
                mogLogProb(p3,mu3,vary3,x_5);...
                mogLogProb(p4,mu4,vary4,x_5);...
                mogLogProb(p5,mu5,vary5,x_5);...
                mogLogProb(p6,mu6,vary6,x_5);...
                mogLogProb(p7,mu7,vary7,x_5)];
    [~,maxind5] = max(train5);
    train5errors = sum( maxind5 ~= 5);
    
        train6 = [mogLogProb(p1,mu1,vary1,x_6);...
                mogLogProb(p2,mu2,vary2,x_6);...
                mogLogProb(p3,mu3,vary3,x_6);...
                mogLogProb(p4,mu4,vary4,x_6);...
                mogLogProb(p5,mu5,vary5,x_6);...
                mogLogProb(p6,mu6,vary6,x_6);...
                mogLogProb(p7,mu7,vary7,x_6)];
    [~,maxind6] = max(train6);
    train6errors = sum( maxind6 ~= 6);
    
        train7 = [mogLogProb(p1,mu1,vary1,x_7);...
                mogLogProb(p2,mu2,vary2,x_7);...
                mogLogProb(p3,mu3,vary3,x_7);...
                mogLogProb(p4,mu4,vary4,x_7);...
                mogLogProb(p5,mu5,vary5,x_7);...
                mogLogProb(p6,mu6,vary6,x_7);...
                mogLogProb(p7,mu7,vary7,x_7)];
    [~,maxind7] = max(train7);
    train7errors = sum( maxind7 ~= 7);
   %% 
    train_errors = zeros(1,7);
    train_errors(1) = train1errors;
    train_errors(2) = train2errors;
    train_errors(3) = train3errors;
    train_errors(4) = train4errors;
    train_errors(5) = train5errors;
    train_errors(6) = train6errors;
    train_errors(7) = train7errors;
    
    train_probs = zeros(7,n);
%     train_probs(1,:) = maxval(maxind1' ==1);
%     train_probs(2,:) = maxind2' ==2;
%     train_probs(3,:) = maxind3' ==3;
%     train_probs(4,:) = maxind4' ==4;
%     train_probs(5,:) = maxind5' ==5;
%     train_probs(6,:) = maxind6' ==6;
%     train_probs(7,:) = maxind7';
    
    pred = train_probs;
    errors = train_errors;
end